-- =====================================================
-- СХЕМА МОДУЛЯ «МЕХАНИЗАЦИЯ»
-- Выполнить в Supabase SQL Editor (один раз).
-- Таблицы создаются, только если их ещё нет (if not exists),
-- существующие данные не затрагиваются.
-- Админ-проверка: is_current_admin() — уже существует в БД
-- (module_access, module_name = 'admin').
-- =====================================================

-- Техника
create table if not exists public.vehicles (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    type text default 'Без категории',
    model text,
    notes text,
    plate text,
    inv_number text,
    current_hours integer default 0,
    zero_hours integer default 0,
    step_hours integer default 125,
    vin_number text,
    inspection_date date,
    insurance_date date,
    tags text default ''
);

-- Задачи по технике
create table if not exists public.vehicle_tasks (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    vehicle_id bigint references public.vehicles (id) on delete cascade,
    vehicle_name text,
    text text not null,
    is_completed boolean not null default false
);

-- Водители и механизаторы
create table if not exists public.fleet_drivers (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text not null unique
);

-- Категории техники
create table if not exists public.fleet_categories (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text not null unique
);

-- Теги статусов
create table if not exists public.fleet_tags (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text not null unique,
    color text default '#e2e8f0'
);

-- =====================================================
-- RLS: чтение — всем авторизованным,
-- запись/изменение/удаление — только админам
-- =====================================================

alter table public.vehicles enable row level security;
alter table public.vehicle_tasks enable row level security;
alter table public.fleet_drivers enable row level security;
alter table public.fleet_categories enable row level security;
alter table public.fleet_tags enable row level security;

do $$
declare t text;
begin
    foreach t in array array[
        'vehicles', 'vehicle_tasks',
        'fleet_drivers', 'fleet_categories', 'fleet_tags'
    ] loop
        if not exists (
            select 1 from pg_policies
            where schemaname = 'public'
              and tablename = t
              and policyname = t || '_select_auth'
        ) then
            execute format(
                'create policy %I on public.%I for select to authenticated using (true);',
                t || '_select_auth', t
            );
        end if;

        if not exists (
            select 1 from pg_policies
            where schemaname = 'public'
              and tablename = t
              and policyname = t || '_admin_all'
        ) then
            execute format(
                'create policy %I on public.%I for all to authenticated using (is_current_admin()) with check (is_current_admin());',
                t || '_admin_all', t
            );
        end if;
    end loop;
end $$;
